ithub 100524/accounts/urls.py
from django.urls import include, path

from accounts.views import SignupPageView, personal_profile

app_name = 'accounts'
urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("signup/", SignupPageView.as_view(), name="signup"),
    path("me/", personal_profile, name="personal_profile"),
]

ithub 100524/ithub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('news/', include('news.urls')),
    path("accounts/", include("accounts.urls")),
    path("activities/", include("activities.urls")),
]
urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

ithub 100524/main/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views
app_name = 'main'
urlpatterns = [
    path('', views.index, name='home'),
    path('privacy/', TemplateView.as_view(template_name='public/main/privacy.html'), name='privacy_page'),
]

ithub 100524/templates/includes/carousel.html
{% load static %}
<div id="default-carousel" class="relative w-full" data-carousel="slide">
            <!-- Carousel wrapper -->
            <div class="relative h-56 overflow-hidden md:h-96 lg:h-[700px] ">
                <!-- Item 1 -->
                <div class="hidden duration-700 ease-in-out" data-carousel-item>
                    <img src="{% static 'images/main-slider/main-slider1.jpeg' %}"
                         class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="...">
                </div>
                <!-- Item 2 -->
                <div class="hidden duration-700 ease-in-out" data-carousel-item>
                    <img src="{% static 'images/main-slider/main-slider2.jpeg' %}"
                         class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="...">
                </div>
                <!-- Item 3 -->
                <div class="hidden duration-700 ease-in-out" data-carousel-item>
                    <img src="{% static 'images/main-slider/main-slider3.jpeg' %}"
                         class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="...">
                </div>
                <!-- Item 4 -->
                <div class="hidden duration-700 ease-in-out" data-carousel-item>
                    <img src="{% static 'images/main-slider/main-slider4.jpeg' %}"
                         class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="...">
                </div>
                <!-- Item 5 -->
                <div class="hidden duration-700 ease-in-out" data-carousel-item>
                     <img src="{% static 'images/main-slider/main-slider5.jpeg' %}"
                         class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="...">
                </div>
            </div>
            <!-- Slider indicators -->
            <div class="absolute z-30 flex -translate-x-1/2 bottom-5 left-1/2 space-x-3 rtl:space-x-reverse">
                <button type="button" class="w-3 h-3 rounded-full" aria-current="true" aria-label="Slide 1"
                        data-carousel-slide-to="0"></button>
                <button type="button" class="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 2"
                        data-carousel-slide-to="1"></button>
                <button type="button" class="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 3"
                        data-carousel-slide-to="2"></button>
                <button type="button" class="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 4"
                        data-carousel-slide-to="3"></button>
                <button type="button" class="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 5"
                        data-carousel-slide-to="4"></button>
            </div>
        </div>

ithub 100524/templates/includes/header.html
{% load thumbnail %}
{% load static %}



<nav class="border-gray-200 dark:bg-gray-900">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a class="flex flex-col" href="{% url 'main:home' %}">
            <span class="text-white text-5xl font-extrabold">IT-HUB</span>
            <span class="text-white text-lg pt-1">Научный</span>
            <span class="text-white text-lg">Исследовательский центр</span>
        </a>

        <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
            <div class="px-2 sm:px-6 flex flex-row">
                <a href="https://t.me/it_hub_sgugit" class="px-2"> <img class="size-10 " src="{% static 'images/telegram.svg' %}" alt=""></a>
                <a href="https://vk.com/it_hub_sgugit" class="px-2"><img class="size-10 " src="{% static 'images/vkontakte.svg' %}" alt=""></a>

            </div>
            <button type="button"
                    class="px-2 flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600"
                    id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown"
                    data-dropdown-placement="bottom">
                <span class="sr-only">Open user menu</span>
                {% if user.is_authenticated and user.image_profile.url %}
                    {% thumbnail user.image_profile "80x80" crop="center" as im %}
                        <img src="{{ im.url }}" class="w-8 h-8 rounded-full bg-white">
                    {% empty %}
                        <img src="{% static 'images/unknown-user.svg' %}" class="w-8 h-8 rounded-full bg-white">
                    {% endthumbnail %}
                {% else %}
                    <img src="{% static 'images/unknown-user.svg' %}" class="w-8 h-8 rounded-full bg-white">
                {% endif %}
            </button>
            <!-- Dropdown menu -->
            <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow dark:bg-gray-700 dark:divide-gray-600"
                 id="user-dropdown">
                <div class="px-4 py-3">
                    {% if user.is_authenticated %}

                        <span class="block text-sm text-gray-900 dark:text-white">{{ user.email }}</span>
                        <span class="block text-sm  text-gray-500 truncate dark:text-gray-400">{{ user.email }}</span>

                    {% else %}
                        <span>Авторизуйтесь</span>
                    {% endif %}
                </div>
                <ul class="py-2" aria-labelledby="user-menu-button">
                    {% if user.is_authenticated %}

                        {% with request.resolver_match.view_name as view_name %}
                            {% if view_name  == 'accounts:personal_profile' %}
                                <li>
                                    <a href="{% url 'main:home' %}"
                                       class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Главная</a>
                                </li>
                            {% else %}
                                <li>
                                    <a href="{% url 'accounts:personal_profile' %}"
                                       class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">
                                        Личный кабинет</a>
                                </li>

                            {% endif %}
                        {% endwith %}

                        <li>
                            <a href="{% url 'accounts:logout' %}"
                               class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Выход </a>
                        </li>


                    {% else %}

                        <li>
                            <a href="{% url 'accounts:login' %}"
                               class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Вход
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:signup' %}"
                               class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Регистрация</a>
                        </li>
                    {% endif %}
                </ul>
            </div>


        </div>

    </div>
</nav>