ithub 100524/ithub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('news/', include('news.urls')),
    path("accounts/", include("accounts.urls")),
    path("activities/", include("activities.urls")),
]
urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

ithub 100524/main/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views
app_name = 'main'
urlpatterns = [
    path('', views.index, name='home'),
    path('privacy/', TemplateView.as_view(template_name='public/main/privacy.html'), name='privacy_page'),
]

ithub 100524/news/urls.py
from django.urls import path, include
from . import views

app_name = 'news'

urlpatterns_staff = [
    path('list_news/', views.list_news_staff, name='list_news_staff'),
    path('detail_news/<int:pk>/', views.detail_news_staff, name='detail_news_staff'),
    path('create_news/', views.create_news_staff, name='create_news_staff'),
    path('update_news/<int:pk>/', views.update_news_staff, name='update_news_staff'),
    path('delete_news/<int:pk>/', views.delete_news_staff, name='delete_news_staff'),
]
urlpatterns = [
    path('', views.index, name='list_news'),
    path('<int:pk>/', views.detail, name='detail_news'),
    path('staff/', include(urlpatterns_staff)),


]

ithub 100524/news/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

User = get_user_model()


class News(models.Model):
    title = models.CharField('Название', max_length=150)
    anons = models.CharField('Анонс', max_length=150)
    full_text = models.TextField('Статья')
    datetime_pub = models.DateTimeField('Дата публикации')
    views = models.IntegerField('Просмотры', default=0)
    image = models.ImageField(
        'Изображение', upload_to='news/', blank=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='news',
        verbose_name='Автор'
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("news:detail_news", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

ithub 100524/news/forms.py
import datetime

from django import forms
from django.forms import ModelForm
from django.utils import timezone

from news.models import News


class NewsForm(ModelForm):
    date_pub = forms.DateField(
        label='Дата публикации',
        required=True,
        input_formats=['%d/%m/%Y'],
        widget=forms.DateInput(
            format='%d/%m/%Y',
            attrs={
                'type': 'date_mod'})
    )

    time_pub = forms.TimeField(
        label='Время публикации',
        required=True,
        input_formats=['%H:%M'],
        widget=forms.TimeInput(format='%H:%M', attrs={'type': 'time'})
    )

    class Meta:
        model = News
        fields = ['title', 'anons', 'full_text', 'image']

    def __init__(self, *args, **kwargs):

        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        instance = kwargs.get('instance', None)
        if instance is not None:
            date_pub = instance.datetime_pub
            if date_pub:
                # Set initial values for the date and time fields
                self.fields['date_pub'].initial = date_pub.date()
                self.fields['time_pub'].initial = date_pub.time()


    def save(self, commit=True):
        instance = super().save(commit=False)
        date_pub = self.cleaned_data['date_pub']
        time_pub = self.cleaned_data['time_pub']
        datetime_pub = datetime.datetime.combine(date_pub,
                                                 time_pub)
        if timezone.is_naive(datetime_pub):
            datetime_pub = timezone.make_aware(datetime_pub, timezone.get_current_timezone())
        instance.datetime_pub = datetime_pub
        instance.author = self.user
        if commit:
            instance.save()
        return instance

ithub 100524/news/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render, get_object_or_404, redirect

from news.forms import NewsForm
from news.models import News


def index(request):
    news = News.objects.all()
    context = {'news_list': news}
    return render(request, 'public/news/index.html', context)


def detail(request, pk):
    news = get_object_or_404(News, pk=pk)

    news.views += 1
    news.save()

    context = {'news_detail': news}
    return render(request, 'public/news/detail.html', context)


@staff_member_required
def list_news_staff(request):
    news = News.objects.all()
    context = {'news_list': news}
    return render(request, 'staff/news/list.html', context)


@staff_member_required
def detail_news_staff(request, pk):
    news_obj = get_object_or_404(News, id=pk)
    context = {'article': news_obj}
    return render(request, 'staff/news/detail.html', context)


@staff_member_required
def create_news_staff(request):
    form = NewsForm(
        request.POST or None,
        files=request.FILES or None,
        user=request.user
    )
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('news:list_news_staff')

    return render(request, 'staff/news/create_edit.html', {'form': form})


@staff_member_required()
def update_news_staff(request, pk):
    news_obj = get_object_or_404(News, id=pk)

    form = NewsForm(
        request.POST or None,
        files=request.FILES or None,
        user=request.user,
        instance=news_obj
    )
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('news:detail_news_staff', pk=pk)

    context = {
        'is_edit': True,
        'form': form,
    }
    return render(request, 'staff/news/create_edit.html', context)


@staff_member_required
def delete_news_staff(request, pk):
    news_obj = get_object_or_404(News, id=pk)
    news_obj.delete()
    return redirect('news:list_news_staff')

ithub 100524/templates/staff/news/create_edit.html
{% extends "_base_profile.html" %}

{% load i18n %}
{% load thumbnail %}
{% load static %}
{% load user_filters %}
{% block content %}
    <div class="max-w-5xl mx-auto">


        <div class="grid grid-cols-12 mt-10">
            {% include 'staff/accounts/staff_sidebar.html' %}
            <div class="p-10  text-medium text-gray-400 bg-gray-800 rounded-lg  col-span-9">
                <h3 class="text-lg font-bold text-white mb-2">
                    {% if is_edit %}
                    Изменить Новость
                    {% else %}
                        Создать новость
                    {% endif %}

                </h3>
                <div class="pt-10">

                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="accent-red-600">
                                    {{ error|escape }}
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="accent-red-600">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <form class="" method="POST" enctype="multipart/form-data">

                        {% csrf_token %}
                        {% for field in form %}

                            <div class="relative z-0 w-full mb-5 group pt-10 "
                                    {% if field.field.required %}
                                 aria-required="true"
                                    {% else %}
                                 aria-required="false"
                                    {% endif %}
                            >

                                {% if field.field.widget.input_type == 'file' %}
                                    <label for="{{ field.id_for_label }}"
                                           class="block  text-sm font-medium text-white pb-5">
                                        {{ field.label }}
                                        {% if field.field.required %}
                                            <span class="accent-red-600">*</span>
                                        {% endif %}
                                    </label>
                                    {{ field|without_placeholder|addclass:"block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 text-gray-400 focus:outline-none bg-gray-700 border-gray-600 placeholder-gray-400" }}

                                {% elif field.field.widget.input_type == 'select' %}
                                    <label for="{{ field.id_for_label }}"
                                           class="block  text-sm font-medium text-white mb-5">
                                        {{ field.label }}
                                        {% if field.field.required %}
                                            <span class="accent-red-600">*</span>
                                        {% endif %}
                                    </label>
                                    {{ field|without_placeholder|addclass:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" }}
                                {% elif field.field.widget.input_type == 'date_mod' %}

                                    <label for="{{ field.id_for_label }}"
                                           class="block  text-sm font-medium text-white mb-5">
                                        {{ field.label }}
                                        {% if field.field.required %}
                                            <span class="accent-red-600">*</span>
                                        {% endif %}
                                    </label>

                                    <div class="relative max-w-sm">
                                        <div class="absolute inset-y-0 start-0 flex items-center ps-3.5 pointer-events-none">
                                            <svg class="w-4 h-4  text-gray-400" aria-hidden="true"
                                                 xmlns="http://www.w3.org/2000/svg" fill="currentColor"
                                                 viewBox="0 0 20 20">
                                                <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
                                            </svg>
                                        </div>
                                        {{ field|add_placeholder:'Дата публикации'|addclass:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" }}
                                    </div>

                                {% elif field.field.widget.input_type == 'time' %}

                                    <div class="relative max-w-sm">

                                        <label for="{{ field.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"> {{ field.label }}</label>
                                        <div class="relative">
                                            <div class="absolute inset-y-0 end-0 top-0 flex items-center pe-3.5 pointer-events-none">
                                                <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                                                    <path fill-rule="evenodd" d="M2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10S2 17.523 2 12Zm11-4a1 1 0 1 0-2 0v4a1 1 0 0 0 .293.707l3 3a1 1 0 0 0 1.414-1.414L13 11.586V8Z" clip-rule="evenodd"/>
                                                </svg>
                                            </div>
                                        {{ field|add_placeholder:"Время публикации"|addclass:"bg-gray-50 border leading-none border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" }}
                                        </div>

                                    </div>

                                {% else %}
                                    {{ field|without_placeholder|addclass:'block py-2.5 px-0 w-full text-sm text-white bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer' }}
                                    <label for="{{ field.id_for_label }}"
                                           class="peer-focus:font-medium absolute text-sm text-white dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
                                        {{ field.label }}
                                        {% if field.field.required %}
                                            <span class="accent-red-600">*</span>
                                        {% endif %}
                                    </label>

                                {% endif %}


                            </div>

                        {% endfor %}

                        <button type="submit"
                                class="inline-flex items-center mt-10 px-7 py-3 text-sm font-medium text-center text-white bg-gray-600 rounded-lg hover:bg-gray-300 focus:ring-4 focus:outline-none focus:ring-blue-300">
                            <span>Отправить</span>
                            <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true"
                                 xmlns="http://www.w3.org/2000/svg"
                                 fill="none" viewBox="0 0 14 10">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                      stroke-width="2"
                                      d="M1 5h12m0 0L9 1m4 4L9 9"></path>
                            </svg>
                        </button>
                    </form>
                </div>
            </div>

        </div>
    </div>


    <script src="{% static 'js/datepicker.js' %}"></script>
    <script>
        var datepickerEl = document.getElementById("id_date_pub");
        // Localization settings for Russian language
        new Datepicker(datepickerEl, {
            language: 'ru',
            autohide: true,
            clearBtn: true,
            minDate: {% now 'd/m/Y' %},
            format: 'dd/mm/yyyy',
            todayBtn: true,
            todayHighlight: true,
        });

    </script>
{% endblock %}

ithub 100524/templates/staff/news/detail.html
{% extends "_base_profile.html" %}

{% load i18n %}
{% load thumbnail %}
{% load static %}
{% load user_filters %}
{% block content %}
      <div class="max-w-5xl mx-auto">


        <div class="grid grid-cols-12 mt-10">
            {% include 'staff/accounts/staff_sidebar.html' %}
            <div class="p-10  text-medium text-gray-400 bg-gray-800 rounded-lg  col-span-9 ">
                <div class="flex flex-row">
                    <a class="ml-auto text-md font-bold text-pink-500 mb-2 hover:text-green-400"
                       href="{% url 'news:list_news_staff' %}">Перейти ко всем новостям</a>
                </div>


        <div class="max-w-3xl mx-auto">
            <div class="h-9"></div>
            <div class=" p-10">

                <h1 class="text-5xl font-bold">{{ article.title }}</h1>
                <div class="h-9"></div>
                <p class="text-lg">{{ article.full_text }}</p>
                <div class="h-9"></div>

                {% thumbnail article.image "768x540" crop="center" as im %}
                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="">
                {% empty %}
                    {% with 'http://'|add:request.get_host|add:STATIC_URL|add:'images/intelect-image.jpg' as path %}
                        {% thumbnail path "768x540" crop="center" as im %}
                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                        {% endthumbnail %}
                    {% endwith %}
                {% endthumbnail %}
                    <div class="mt-5 flex flex-row">
                                <a href="{% url 'news:update_news_staff'  article.id %}"
                                   class="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">Изменить</a>
                                <a href="{% url 'news:delete_news_staff'  article.id %}"
                                   class="ml-auto focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">Удалить</a>
                            </div>
                <div class="p-1 flex-row flex pt-10">
                    <a class="flex flex-row text-md" href="">Поделиться </a> <img src="{% static 'images/share.svg' %}"
                                                                                  alt="">
                    <div class="ml-auto">
                        <span>{{ article.datetime_pub|date:"j M Y" }} •</span>
                        <span>{{ article.views }}
                            {% if article.views == 1 %}
                                просмотр
                            {% elif article.views < 5 %}
                                просмотра
                            {% else %}
                                просмотров
                            {% endif %}
                                </span>

                    </div>

                </div>

            </div>
        </div>
        <div class="h-9"></div>

        <div class="h-9"></div>
        <div class="h-9"></div>

    </div>
    </div>
    </div>
{% endblock %}

ithub 100524/templates/staff/news/list.html
{% extends "_base_profile.html" %}

{% load i18n %}
{% load thumbnail %}
{% load static %}
{% load user_filters %}
{% block content %}
    <div class="max-w-5xl mx-auto">


        <div class="grid grid-cols-12 mt-10">
            {% include 'staff/accounts/staff_sidebar.html' %}
            <div class="p-10  text-medium text-gray-400 bg-gray-800 rounded-lg  col-span-9 ">
                <div class="flex flex-row">
                    <h3 class="text-2xl font-bold text-white mb-2">Редактирование новостей</h3>
                    <a class="ml-auto text-md font-bold text-pink-500 mb-2 hover:text-green-400"
                       href="{% url 'news:create_news_staff' %}">Создать новую</a>
                </div>
                <div class="grid grid-cols-2 gap-1 ">

                               {% if not news_list %}
                        <h3 class="text-lg font-bold text-white mb-2">Отсутствуют</h3>

                    {% endif %}
                    {% for article in news_list %}



                        <div class="max-w-sm pt-10 ">
                            <a href="{% url 'news:detail_news_staff' article.id %}">
                                {% thumbnail article.image "304x171" crop="center" as im %}
                                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="">
                                {% empty %}
                                    {% with 'http://'|add:request.get_host|add:STATIC_URL|add:'images/intelect-image.jpg' as path %}
                                        {% thumbnail path "304x171" crop="center" as im %}
                                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                                        {% endthumbnail %}
                                    {% endwith %}
                                {% endthumbnail %}
                                <div class="pt-3">

                                    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                                        {{ article.title }}</h5>

                                    <p class="mb-3 text-lg font-normal text-gray-700 dark:text-gray-400">{{ article.full_text|truncatechars:78 }}</p>


                                </div>

                                <div class="p-1 flex-row flex">

                                    <span>{{ article.datetime_pub|date:"j M Y" }} •</span>
                                    <span>{{ article.views }}
                                        {% if article.views == 1 %}
                                            просмотр
                                        {% elif  article.views == 0 %}
                                            просмотров
                                        {% elif  article.views < 5 %}
                                            просмотра
                                        {% else %}
                                            просмотров
                                        {% endif %}
                                </span>

                                </div>
                            </a>
                            <div class="mt-5">
                                <a href="{% url 'news:update_news_staff'  article.id %}"
                                   class="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">Изменить</a>
                                <a href="{% url 'news:delete_news_staff'  article.id %}"
                                   class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">Удалить</a>
                            </div>
                        </div>


                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}