ithub 100524/activities/urls.py
from django.urls import path, include
from . import views
app_name = 'activities'

urlpatterns_staff = [
    path('list_activities/', views.list_activities_staff, name='list_activities_staff'),
    path('detail_news/<int:pk>/', views.detail_activities_staff, name='detail_activities_staff'),
    path('create_activities/', views.create_activities_staff, name='create_activities_staff'),
    path('update_activities/<int:pk>/', views.update_activities_staff, name='update_activities_staff'),
    path('delete_activities/<int:pk>/', views.delete_activities_staff, name='delete_activities_staff'),

    path('list_requests_activities_staff/', views.list_requests_activities_staff, name='list_requests_activities_staff'),
    path('change_status_activities_staff/<int:pk>/', views.change_status_activities_staff, name='change_status_activities_staff'),
]

urlpatterns_user = [
    path('registration_activities/', views.registration_activities, name='registration_activities'),
    path('my_requests_activities/', views.my_requests_activities, name='my_requests_activities'),
]

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail_activities'),
    path('staff/', include(urlpatterns_staff)),
    path('user/', include(urlpatterns_user)),
]

ithub 100524/ithub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('news/', include('news.urls')),
    path("accounts/", include("accounts.urls")),
    path("activities/", include("activities.urls")),
]
urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

ithub 100524/main/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views
app_name = 'main'
urlpatterns = [
    path('', views.index, name='home'),
    path('privacy/', TemplateView.as_view(template_name='public/main/privacy.html'), name='privacy_page'),
]

ithub 100524/activities/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import UniqueConstraint
from django.urls import reverse

from core.models import CreatedUpdatedModel

User = get_user_model()


class StatusParticipation(models.TextChoices):
    UNKNOWN = ("UNK", "На рассмотрении")
    ACCEPTED = ("ACC", "Принята")
    UNACCEPTED = ("UNA", "Отклонена")


class Activities(CreatedUpdatedModel):
    title = models.CharField('Название', max_length=150)
    anons = models.CharField('Анонс', max_length=150)
    full_text = models.TextField('Полный текст')
    datetime_pub = models.DateTimeField('Дата Мероприятия')
    views = models.IntegerField('Просмотры', default=0)
    image = models.ImageField(
        'Изображение', upload_to='activities/', blank=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='activities',
        verbose_name='Автор'
    )

    def __str__(self):
        return f"{self.title} Время: {self.datetime_pub.strftime('%d/%m/%Y %H:%M')}"

    def get_absolute_url(self):
        return reverse("activities:detail_activities", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = 'Мероприятие'
        verbose_name_plural = 'Мероприятия'


class ParticipationActivities(CreatedUpdatedModel):
    first_name = models.CharField("Имя", max_length=100 )
    surname = models.CharField("Фамилия", max_length=100)
    last_name = models.CharField("Отчество", max_length=100)
    email = models.EmailField(max_length = 255, verbose_name = 'Емайл')

    activity = models.ForeignKey(
        Activities, verbose_name='Мероприятие',
        on_delete=models.CASCADE,
        related_name='participation_activities')
    created_by = models.ForeignKey(
        User, verbose_name='Участник',
        on_delete=models.CASCADE,
        related_name='participation_activities')
    education_entity = models.CharField('Образовательное учреждение',
                                        max_length=150,
                                        blank=True,
                                        null=True)
    status = models.CharField(
        max_length=3,
        choices=StatusParticipation.choices,
        default=StatusParticipation.UNKNOWN,
    )

    class Meta:
        verbose_name = 'Участие в мероприятии'
        verbose_name_plural = 'Участие в мероприятиях'
        constraints = [
            UniqueConstraint(
                fields=['activity', 'created_by'], name='unique_participation'),
        ]

    def __str__(self):
        return f'{self.activity} | {self.created_by} | {self.get_status_display()}'

ithub 100524/activities/forms.py
import datetime

from django import forms
from django.forms import ModelForm
from django.utils import timezone

from activities.models import Activities, ParticipationActivities, StatusParticipation


class ActivitiesForm(ModelForm):
    date_pub = forms.DateField(
        label='Дата публикации',
        required=True,
        input_formats=['%d/%m/%Y'],
        widget=forms.DateInput(
            format='%d/%m/%Y',
            attrs={
                'type': 'date_mod'})
    )

    time_pub = forms.TimeField(
        label='Время публикации',
        required=True,
        input_formats=['%H:%M'],
        widget=forms.TimeInput(format='%H:%M', attrs={'type': 'time'})
    )

    class Meta:
        model = Activities
        fields = ['title', 'anons', 'full_text', 'image']

    def __init__(self, *args, **kwargs):

        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        instance = kwargs.get('instance', None)
        if instance is not None:
            date_pub = instance.datetime_pub
            if date_pub:
                # Set initial values for the date and time fields
                self.fields['date_pub'].initial = date_pub.date()
                self.fields['time_pub'].initial = date_pub.time()

    def save(self, commit=True):
        instance = super().save(commit=False)
        date_pub = self.cleaned_data['date_pub']
        time_pub = self.cleaned_data['time_pub']
        datetime_pub = datetime.datetime.combine(date_pub,
                                                 time_pub)
        if timezone.is_naive(datetime_pub):
            datetime_pub = timezone.make_aware(datetime_pub, timezone.get_current_timezone())
        instance.datetime_pub = datetime_pub
        instance.author = self.user
        if commit:
            instance.save()
        return instance


class ActivitiesRegistrationForm(ModelForm):
    class Meta:
        model = ParticipationActivities
        fields = [
            'first_name',
            'surname',
            'last_name',
            'email',
            'activity',
            'education_entity',
        ]

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if self.user:
            self.fields['first_name'].initial = self.user.first_name or None
            self.fields['surname'].initial = self.user.surname or None
            self.fields['last_name'].initial = self.user.last_name or None
            self.fields['email'].initial = self.user.email or None

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.created_by = self.user
        if commit:
            instance.save()
        return instance

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if first_name:
            return first_name.capitalize()
        return first_name

    def clean_surname(self):
        surname = self.cleaned_data.get('surname')
        if surname:
            return surname.capitalize()
        return surname

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')
        if last_name:
            return last_name.capitalize()
        return last_name


class ChangeStatusParticipationActivitiesForm(ModelForm):
    class Meta:
        model = ParticipationActivities
        fields = ['status']
        widgets = {
            'status': forms.RadioSelect(),

        }

ithub 100524/activities/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from activities.forms import ActivitiesForm, ActivitiesRegistrationForm, ChangeStatusParticipationActivitiesForm
from activities.models import Activities, ParticipationActivities, StatusParticipation


def detail(request, pk):
    activities_obj = get_object_or_404(Activities, pk=pk)

    activities_obj.views += 1
    activities_obj.save()

    context = {'activities_obj': activities_obj}
    return render(request, 'public/activities/detail.html', context)


@login_required
def registration_activities(request):
    form = ActivitiesRegistrationForm(
        request.POST or None,
        user=request.user
    )
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('activities:my_requests_activities')

    return render(request, 'user/activities/registration_activities.html', {'form': form})


@login_required
def my_requests_activities(request):
    my_requests = ParticipationActivities.objects.filter(created_by=request.user)
    return render(request, 'user/activities/my_requests_activities.html', {'my_requests': my_requests})


@staff_member_required
def list_activities_staff(request):
    activities = Activities.objects.all()
    context = {'activities_list': activities}
    return render(request, 'staff/activities/list.html', context)


@staff_member_required
def detail_activities_staff(request, pk):
    activities_obj = get_object_or_404(Activities, id=pk)
    context = {'activities_obj': activities_obj}
    return render(request, 'staff/activities/detail.html', context)


@staff_member_required
def create_activities_staff(request):
    form = ActivitiesForm(
        request.POST or None,
        files=request.FILES or None,
        user=request.user
    )
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('activities:list_activities_staff')

    return render(request, 'staff/activities/create_edit.html', {'form': form})


@staff_member_required()
def update_activities_staff(request, pk):
    activities_obj = get_object_or_404(Activities, id=pk)

    form = ActivitiesForm(
        request.POST or None,
        files=request.FILES or None,
        user=request.user,
        instance=activities_obj
    )
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('activities:detail_activities_staff', pk=pk)

    context = {
        'is_edit': True,
        'form': form,
    }
    return render(request, 'staff/activities/create_edit.html', context)


@staff_member_required
def delete_activities_staff(request, pk):
    activities_obj = get_object_or_404(Activities, id=pk)
    activities_obj.delete()
    return redirect('activities:list_activities_staff')


@staff_member_required
def list_requests_activities_staff(request):
    requests_activities = ParticipationActivities.objects.all()
    q = request.GET.get('q')
    human_value_q = dict(StatusParticipation.choices).get(q)
    if human_value_q:
        requests_activities = requests_activities.filter(status=q)
    context = {
        'form': ChangeStatusParticipationActivitiesForm(),
        'requests_activities': requests_activities,
        'human_value_q': human_value_q
    }
    return render(request, 'staff/activities/list_requests.html', context)


@staff_member_required
def change_status_activities_staff(request, pk, ):
    obj = get_object_or_404(ParticipationActivities, pk=pk)
    if request.method == 'POST':
        form = ChangeStatusParticipationActivitiesForm(request.POST, instance=obj)
        if form.is_valid():
            obj.save()
    return redirect('activities:list_requests_activities_staff')

ithub 100524/templates/staff/activities/detail.html
{% extends "_base_profile.html" %}

{% load i18n %}
{% load thumbnail %}
{% load static %}
{% load user_filters %}
{% block content %}
      <div class="max-w-5xl mx-auto">


        <div class="grid grid-cols-12 mt-10">
            {% include 'staff/accounts/staff_sidebar.html' %}
            <div class="p-10  text-medium text-gray-400 bg-gray-800 rounded-lg  col-span-9 ">
                <div class="flex flex-row">
                    <a class="ml-auto text-md font-bold text-pink-500 mb-2 hover:text-green-400"
                       href="{% url 'activities:list_activities_staff' %}">Перейти ко всем мероприятиям</a>
                </div>


        <div class="max-w-3xl mx-auto">
            <div class="h-9"></div>
            <div class=" p-10">

                <h1 class="text-5xl font-bold">{{ activities_obj.title }}</h1>
                <div class="h-9"></div>
                <p class="text-lg">{{ activities_obj.full_text }}</p>
                <div class="h-9"></div>

                {% thumbnail activities_obj.image "768x540" crop="center" as im %}
                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="">
                {% empty %}
                    {% with 'http://'|add:request.get_host|add:STATIC_URL|add:'images/intelect-image.jpg' as path %}
                        {% thumbnail path "768x540" crop="center" as im %}
                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                        {% endthumbnail %}
                    {% endwith %}
                {% endthumbnail %}
                    <div class="mt-5 flex flex-row">
                                <a href="{% url 'activities:update_activities_staff'  activities_obj.id %}"
                                   class="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">Изменить</a>
                                <a href="{% url 'activities:delete_activities_staff'  activities_obj.id %}"
                                   class="ml-auto focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">Удалить</a>
                            </div>
                <div class="p-1 flex-row flex pt-10">
                    <a class="flex flex-row text-md" href="">Поделиться </a> <img src="{% static 'images/share.svg' %}"
                                                                                  alt="">
                    <div class="ml-auto">
                        <span>{{ activities_obj.datetime_pub|date:"j M Y" }} •</span>
                        <span>{{ activities_obj.views }}
                            {% if activities_obj.views == 1 %}
                                просмотр
                            {% elif activities_obj.views < 5 %}
                                просмотра
                            {% else %}
                                просмотров
                            {% endif %}
                                </span>

                    </div>

                </div>

            </div>
        </div>
        <div class="h-9"></div>

        <div class="h-9"></div>
        <div class="h-9"></div>

    </div>
    </div>
    </div>
{% endblock %}

ithub 100524/templates/staff/activities/list.html
{% extends "_base_profile.html" %}

{% load i18n %}
{% load thumbnail %}
{% load static %}
{% load user_filters %}
{% block content %}
    <div class="max-w-5xl mx-auto">


        <div class="grid grid-cols-12 mt-10">
            {% include 'staff/accounts/staff_sidebar.html' %}
            <div class="p-10  text-medium text-gray-400 bg-gray-800 rounded-lg  col-span-9 ">
                <div class="flex flex-row">
                    <h3 class="text-2xl font-bold text-white mb-2">Редактирование Мероприятий</h3>
                    <a class="ml-auto text-md font-bold text-pink-500 mb-2 hover:text-green-400"
                       href="{% url 'activities:create_activities_staff' %}">Создать новое</a>
                </div>
                <div class="grid grid-cols-2 gap-1 ">
                    {% if not activities_list %}
                        <h3 class="text-lg font-bold text-white mb-2">Отсутствуют</h3>

                    {% endif %}
                    {% for activities_obj in activities_list %}



                        <div class="max-w-sm pt-10 ">
                            <a href="#">
                                {% thumbnail activities_obj.image "304x171" crop="center" as im %}
                                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="">
                                {% empty %}
                                    {% with 'http://'|add:request.get_host|add:STATIC_URL|add:'images/intelect-image.jpg' as path %}
                                        {% thumbnail path "304x171" crop="center" as im %}
                                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                                        {% endthumbnail %}
                                    {% endwith %}
                                {% endthumbnail %}
                                <div class="pt-3">

                                    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                                        {{ activities_obj.title }}</h5>

                                    <p class="mb-3 text-lg font-normal text-gray-700 dark:text-gray-400">{{ activities_obj.full_text|truncatechars:78 }}</p>


                                </div>

                                <div class="p-1 flex-row flex">

                                    <span>{{ activities_obj.datetime_pub|date:"j M Y" }} •</span>
                                    <span>{{ activities_obj.views }}
                                        {% if activities_obj.views == 1 %}
                                            просмотр
                                        {% elif  activities_obj.views == 0 %}
                                            просмотров
                                        {% elif  activities_obj.views < 5 %}
                                            просмотра
                                        {% else %}
                                            просмотров
                                        {% endif %}
                                </span>

                                </div>
                            </a>
                            <div class="mt-5">
                                <a href="{% url 'activities:update_activities_staff'  activities_obj.id %}"
                                   class="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">Изменить</a>
                                <a href="{% url 'activities:delete_activities_staff'  activities_obj.id %}"
                                   class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">Удалить</a>
                            </div>
                        </div>


                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}

ithub 100524/templates/staff/activities/list_requests.html
{% extends "_base_profile.html" %}

{% load i18n %}
{% load thumbnail %}
{% load static %}
{% load user_filters %}
{% block content %}
    <div class="max-w-5xl mx-auto">


        <div class="grid grid-cols-12 mt-10">
            {% include 'staff/accounts/staff_sidebar.html' %}
            <div class="p-10  text-medium text-gray-400 bg-gray-800 rounded-lg  col-span-9 ">
                <div class="flex flex-row">
                    <h3 class="text-2xl font-bold text-white mb-2">Поданные заявки на мероприятия
                    {%  if  human_value_q  %}
                        по типу:
                        {{ human_value_q }}
                        {% endif %}
                    </h3>

                </div>


                <div class="grid grid-cols-2 gap-1 ">
                    {% if not requests_activities %}
                        <h3 class="text-lg font-bold text-white mb-2">Отсутствуют</h3>

                    {% endif %}
                    {% for request_received in requests_activities %}

                        {% with request_received.activity as activities_obj %}

                            <div class="max-w-sm pt-10 ">
                                {% thumbnail activities_obj.image "304x171" crop="center" as im %}
                                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="">
                                {% empty %}
                                    {% with 'http://'|add:request.get_host|add:STATIC_URL|add:'images/intelect-image.jpg' as path %}
                                        {% thumbnail path "304x171" crop="center" as im %}
                                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                                        {% endthumbnail %}
                                    {% endwith %}
                                {% endthumbnail %}
                                <div class="pt-3">

                                    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                                        {{ activities_obj.title }}</h5>

                                    <p class="mb-3 text-lg font-normal text-gray-700 dark:text-gray-400">{{ activities_obj.full_text|truncatechars:30 }}</p>


                                </div>
                            </div>
                            <div class="max-w-sm pt-10 ">
                                <div class="p-1 flex-col flex">
                                    {% if request_received.id %}
                                        <span>Заявка под номером {{ request_received.id }} </span>

                                    {% endif %}
                                    {% if request_received.first_name %}
                                        <span>{{ request_received.first_name }} </span>

                                    {% endif %}
                                    {% if request_received.surname %}
                                        <span>{{ request_received.surname }} </span>

                                    {% endif %}
                                    {% if request_received.last_name %}
                                        <span>{{ request_received.last_name }} </span>

                                    {% endif %}
                                    {% if request_received.email %}
                                        <span>{{ request_received.email }} </span>

                                    {% endif %}
                                    {% if request_received.education_entity %}
                                        <span>{{ request_received.education_entity }} </span>

                                    {% endif %}

                                    <div class="mt-10">
                                        <form method="POST"
                                              action="{% url 'activities:change_status_activities_staff' request_received.pk %}">
                                            {% csrf_token %}
                                            {% if request_received.status == 'UNK' %}
                                                <span class="focus:outline-none text-white bg-yellow-100 hover:bg-yellow-800 focus:ring-4 focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-yellow-400 dark:hover:bg-yellow-300 dark:focus:ring-yellow-200">{{ request_received.get_status_display }}</span>
                                            {% elif request_received.status == 'UNA' %}
                                                <span class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800">{{ request_received.get_status_display }}</span>
                                            {% elif request_received.status == 'ACC' %}
                                                <span class="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">{{ request_received.get_status_display }}</span>
                                            {% endif %}
                                            <div class="mt-10">

                                                {% for choice in form.status.field.choices %}
                                                    {% if request_received.status == 'UNK' and  choice.0 == 'UNK' %}
                                                    {% elif request_received.status == 'UNA' and   choice.0 == 'UNA' %}
                                                    {% elif request_received.status == 'ACC' and  choice.0 == 'ACC' %}
                                                    {% else %}

                                                        {% if choice.0 == 'UNK' %}
                                                            <label for='{{ form.status.auto_id }}_{{ request_received.pk }}_{{ forloop.counter0 }}'
                                                                   class="inline-flex items-center justify-between w-full p-1 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-white dark:bg-yellow-400 dark:hover:bg-gray-700">
                                                                Поставить
                                                                на рассмотрение
                                                                <input name='{{ form.status.name }}'
                                                                       id='{{ form.status.auto_id }}_{{ request_received.pk }}_{{ forloop.counter0 }}'
                                                                       type='radio' value='{{ choice.0 }}'
                                                                       class="hidden peer"
                                                                       onclick="this.form.submit()"
                                                                >

                                                            </label>
                                                        {% elif choice.0 == 'UNA' %}
                                                            <label for='{{ form.status.auto_id }}_{{ request_received.pk }}_{{ forloop.counter0 }}'
                                                                   class="inline-flex items-center justify-between w-full p-1 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-white dark:bg-red-500 dark:hover:bg-gray-700">
                                                                Отклонить
                                                                <input name='{{ form.status.name }}'
                                                                       id='{{ form.status.auto_id }}_{{ request_received.pk }}_{{ forloop.counter0 }}'
                                                                       type='radio' value='{{ choice.0 }}'
                                                                       class="hidden peer"
                                                                       onclick="this.form.submit()"
                                                                >

                                                            </label>
                                                        {% elif choice.0 == 'ACC' %}
                                                            <label for='{{ form.status.auto_id }}_{{ request_received.pk }}_{{ forloop.counter0 }}'
                                                                   class="inline-flex items-center justify-between w-full p-1 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-white dark:bg-green-800 dark:hover:bg-gray-700">
                                                                Одобрить
                                                                <input name='{{ form.status.name }}'
                                                                       id='{{ form.status.auto_id }}_{{ request_received.pk }}_{{ forloop.counter0 }}'
                                                                       type='radio' value='{{ choice.0 }}'
                                                                       class="hidden peer"
                                                                       onclick="this.form.submit()"
                                                                >

                                                            </label>
                                                        {% endif %}
                                                    {% endif %}



                                                {% endfor %}
                                            </div>

                                        </form>

                                    </div>
                                </div>

                            </div>
                        {% endwith %}

                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}