ithub 100524/accounts/urls.py
from django.urls import include, path

from accounts.views import SignupPageView, personal_profile

app_name = 'accounts'
urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("signup/", SignupPageView.as_view(), name="signup"),
    path("me/", personal_profile, name="personal_profile"),
]

ithub 100524/activities/urls.py
from django.urls import path, include
from . import views
app_name = 'activities'

urlpatterns_staff = [
    path('list_activities/', views.list_activities_staff, name='list_activities_staff'),
    path('detail_news/<int:pk>/', views.detail_activities_staff, name='detail_activities_staff'),
    path('create_activities/', views.create_activities_staff, name='create_activities_staff'),
    path('update_activities/<int:pk>/', views.update_activities_staff, name='update_activities_staff'),
    path('delete_activities/<int:pk>/', views.delete_activities_staff, name='delete_activities_staff'),

    path('list_requests_activities_staff/', views.list_requests_activities_staff, name='list_requests_activities_staff'),
    path('change_status_activities_staff/<int:pk>/', views.change_status_activities_staff, name='change_status_activities_staff'),
]

urlpatterns_user = [
    path('registration_activities/', views.registration_activities, name='registration_activities'),
    path('my_requests_activities/', views.my_requests_activities, name='my_requests_activities'),
]

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail_activities'),
    path('staff/', include(urlpatterns_staff)),
    path('user/', include(urlpatterns_user)),
]

ithub 100524/ithub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('news/', include('news.urls')),
    path("accounts/", include("accounts.urls")),
    path("activities/", include("activities.urls")),
]
urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

ithub 100524/main/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views
app_name = 'main'
urlpatterns = [
    path('', views.index, name='home'),
    path('privacy/', TemplateView.as_view(template_name='public/main/privacy.html'), name='privacy_page'),
]

ithub 100524/news/urls.py
from django.urls import path, include
from . import views

app_name = 'news'

urlpatterns_staff = [
    path('list_news/', views.list_news_staff, name='list_news_staff'),
    path('detail_news/<int:pk>/', views.detail_news_staff, name='detail_news_staff'),
    path('create_news/', views.create_news_staff, name='create_news_staff'),
    path('update_news/<int:pk>/', views.update_news_staff, name='update_news_staff'),
    path('delete_news/<int:pk>/', views.delete_news_staff, name='delete_news_staff'),
]
urlpatterns = [
    path('', views.index, name='list_news'),
    path('<int:pk>/', views.detail, name='detail_news'),
    path('staff/', include(urlpatterns_staff)),


]

ithub 100524/accounts/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.db import models


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Users require an email field')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(max_length = 255, unique = True, verbose_name = 'Емайл')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


    GENDER_CHOICES = (
        ('M', 'М'),
        ('F', 'Ж'),
    )

    first_name = models.CharField("Имя",max_length=100, null=True, blank=True)
    surname = models.CharField("Фамилия",max_length=100, null=True, blank=True)
    last_name = models.CharField("Отчество",max_length=100, null=True, blank=True)
    phone = models.CharField("Номер телефона учащегося",max_length=20, null=True, blank=True)
    sex = models.CharField("Пол",max_length=1, choices=GENDER_CHOICES, null=True, blank=True)
    date_of_birth = models.DateField('Дата рождения',null=True, blank=True)
    citizenship = models.CharField("Гражданство",max_length=100, null=True, blank=True)
    region = models.CharField("Регион",max_length=100, null=True, blank=True)
    image_profile = models.ImageField(
        'Аватар', upload_to='profiles/', blank=True
    )
    objects = UserManager()

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

ithub 100524/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.urls import  reverse_lazy
from django.utils.html import format_html
from django.utils.safestring import mark_safe


class CustomUserCreationForm(UserCreationForm):
    confirm = forms.BooleanField(required=True)

    class Meta:
        model = get_user_model()
        fields = (
            "email",
            "confirm",
        )

    def __init__(self, **kwargs):
        super(CustomUserCreationForm, self).__init__(**kwargs)
        terms_and_conditions = reverse_lazy("main:privacy_page")
        self.fields['confirm'].label = mark_safe((f"Я подтверждаю согласие на обработку персональных данных. <a href='{terms_and_conditions}'>Политика конфиденциальности</a>"))

    field_order = ['email',
                   'password1',
                   'password2',
                   'confirm',
                   ]

    def clean(self):
        cleaned_data = super().clean()
        confirm = cleaned_data.get('confirm')

        if not confirm:
            raise ValidationError('Требуется подтвердить согласие на обработку персональных данных')


class CustomUserCompleteForm(ModelForm):
    date_of_birth = forms.DateField(label='Дата рождения', required=False,
                                    input_formats=['%d/%m/%Y'],
                                    widget=forms.DateInput(
                                        format='%d/%m/%Y',
                                        attrs={
                                            'type': 'date_mod'}))

    class Meta:
        model = get_user_model()
        fields = [
            'first_name',
            'surname',
            'last_name',
            'sex',
            'date_of_birth',
            'citizenship',
            'region',
            'phone',
            'image_profile',
        ]

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if first_name:
            return first_name.capitalize()
        return first_name

    def clean_surname(self):
        surname = self.cleaned_data.get('surname')
        if surname:
            return surname.capitalize()
        return surname

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')
        if last_name:
            return last_name.capitalize()
        return last_name

ithub 100524/accounts/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomUserCreationForm, CustomUserCompleteForm

User = get_user_model()


class SignupPageView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("main:home")
    template_name = "registration/signup.html"


@login_required
def personal_profile(request):
    form = CustomUserCompleteForm(request.POST or None,
                                  files=request.FILES or None,
                                  instance=request.user)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('accounts:personal_profile', )
    context = {'user_profile': request.user,
               'form': form}

    if request.user.is_staff:
        return render(request, 'staff/accounts/me_staff.html', context)
    return render(request, 'user/accounts/me_base.html', context)

ithub 100524/templates/staff/accounts/me_staff.html
{% extends "_base_profile.html" %}

{% load i18n %}
{% load thumbnail %}
{% load static %}
{% load user_filters %}
{% block content %}
    <div class="max-w-5xl mx-auto">


        <div class="grid grid-cols-12 mt-10">
        {% include 'staff/accounts/staff_sidebar.html' %}
            <div class="p-10 text-medium text-gray-400 bg-gray-800 rounded-lg  col-span-9">
                <h3 class="text-lg font-bold text-white mb-2">Личные данные</h3>
                <div class="pt-10">

                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="accent-red-600">
                                    {{ error|escape }}
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="accent-red-600">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <form class="" method="POST" enctype="multipart/form-data">

                        {% csrf_token %}
                        {% for field in form %}

                            <div class="relative z-0 w-full mb-5 group pt-10 "
                                    {% if field.field.required %}
                                 aria-required="true"
                                    {% else %}
                                 aria-required="false"
                                    {% endif %}
                            >

                                {% if field.field.widget.input_type == 'file' %}
                                    <label for="{{ field.id_for_label }}"
                                           class="block  text-sm font-medium text-white pb-5">
                                        {{ field.label }}
                                        {% if field.field.required %}
                                            <span class="accent-red-600">*</span>
                                        {% endif %}
                                    </label>
                                    {{ field|without_placeholder|addclass:"block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 text-gray-400 focus:outline-none bg-gray-700 border-gray-600 placeholder-gray-400" }}

                                {% elif field.field.widget.input_type == 'select' %}
                                    <label for="{{ field.id_for_label }}"
                                           class="block  text-sm font-medium text-white mb-5">
                                        {{ field.label }}
                                        {% if field.field.required %}
                                            <span class="accent-red-600">*</span>
                                        {% endif %}
                                    </label>
                                    {{ field|without_placeholder|addclass:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" }}
                                {% elif field.field.widget.input_type == 'date_mod' %}

                                    <label for="{{ field.id_for_label }}"
                                           class="block  text-sm font-medium text-white mb-5">
                                        {{ field.label }}
                                        {% if field.field.required %}
                                            <span class="accent-red-600">*</span>
                                        {% endif %}
                                    </label>

                                    <div class="relative max-w-sm">
                                        <div class="absolute inset-y-0 start-0 flex items-center ps-3.5 pointer-events-none">
                                            <svg class="w-4 h-4  text-gray-400" aria-hidden="true"
                                                 xmlns="http://www.w3.org/2000/svg" fill="currentColor"
                                                 viewBox="0 0 20 20">
                                                <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
                                            </svg>
                                        </div>
                                        {{ field|add_placeholder:'Дата рождения'|addclass:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" }}
                                    </div>
                                {% else %}
                                    {{ field|without_placeholder|addclass:'block py-2.5 px-0 w-full text-sm text-white bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer' }}
                                    <label for="{{ field.id_for_label }}"
                                           class="peer-focus:font-medium absolute text-sm text-white dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
                                        {{ field.label }}
                                        {% if field.field.required %}
                                            <span class="accent-red-600">*</span>
                                        {% endif %}
                                    </label>

                                {% endif %}


                            </div>

                        {% endfor %}

                        <button type="submit"
                                class="inline-flex items-center mt-10 px-7 py-3 text-sm font-medium text-center text-white bg-gray-600 rounded-lg hover:bg-gray-300 focus:ring-4 focus:outline-none focus:ring-blue-300">
                            <span>Отправить</span>
                            <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true"
                                 xmlns="http://www.w3.org/2000/svg"
                                 fill="none" viewBox="0 0 14 10">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                      stroke-width="2"
                                      d="M1 5h12m0 0L9 1m4 4L9 9"></path>
                            </svg>
                        </button>
                    </form>
                </div>
            </div>

        </div>
    </div>


    <script src="{% static 'js/datepicker.js' %}"></script>
    <script>
        var datepickerEl = document.getElementById("id_date_of_birth");
        // Localization settings for Russian language
        new Datepicker(datepickerEl, {
            language: 'ru',
            autohide: true,
            clearBtn: true,
            minDate: '01/01/1910',
            maxDate: '01/01/2020',
            format: 'dd/mm/yyyy'
        });

    </script>
{% endblock %}

ithub 100524/templates/staff/accounts/staff_sidebar.html
<div class="self-start sticky top-0 col-span-3 ">

    {% with request.resolver_match.view_name as view_name %}
        <ul class="flex-column space-y space-y-4 text-sm font-medium text-gray-400 md:me-4 p-5 bg-gray-700 rounded-lg ">
            <li>
                <a href="{% url 'accounts:personal_profile' %}"
                   class="inline-flex items-center px-4 py-3  active w-full
            {% if view_name == 'accounts:personal_profile' %}
            text-green-400
            {% else %}
            text-gray-300
            {% endif %}


"
                   aria-current="page">
                    <svg class="w-4 h-4 me-2 text-gray-300" aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg"
                         fill="currentColor" viewBox="0 0 20 20">
                        <path d="M10 0a10 10 0 1 0 10 10A10.011 10.011 0 0 0 10 0Zm0 5a3 3 0 1 1 0 6 3 3 0 0 1 0-6Zm0 13a8.949 8.949 0 0 1-4.951-1.488A3.987 3.987 0 0 1 9 13h2a3.987 3.987 0 0 1 3.951 3.512A8.949 8.949 0 0 1 10 18Z"/>
                    </svg>
                    Личные данные
                </a>
            </li>
            <li>
                <a href="{% url 'news:list_news_staff' %}"
                   class="inline-flex items-center px-4 py-3 active w-full
                                        {% if view_name == 'news:list_news_staff' %}
                                                                                text-green-400
                                                                                {% else %}
                                                                                text-gray-300
                                                                                {% endif %}
 "
                   aria-current="page">
                    <svg class="w-4 h-4 me-2 text-gray-300" aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg"
                         fill="currentColor" viewBox="0 0 20 20">
                        <path d="M10 0a10 10 0 1 0 10 10A10.011 10.011 0 0 0 10 0Zm0 5a3 3 0 1 1 0 6 3 3 0 0 1 0-6Zm0 13a8.949 8.949 0 0 1-4.951-1.488A3.987 3.987 0 0 1 9 13h2a3.987 3.987 0 0 1 3.951 3.512A8.949 8.949 0 0 1 10 18Z"/>
                    </svg>
                    Редактирование новостей
                </a>
            </li>
            <li>
                <a href="{% url 'activities:list_activities_staff' %}"
                   class="inline-flex items-center px-4 py-3 active w-full

       {% if view_name == 'activities:list_activities_staff' %}
                                                                                text-green-400
                                                                                {% else %}
                                                                                text-gray-300
                                                                                {% endif %}
"
                   aria-current="page">
                    <svg class="w-4 h-4 me-2 text-gray-300" aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg"
                         fill="currentColor" viewBox="0 0 20 20">
                        <path d="M10 0a10 10 0 1 0 10 10A10.011 10.011 0 0 0 10 0Zm0 5a3 3 0 1 1 0 6 3 3 0 0 1 0-6Zm0 13a8.949 8.949 0 0 1-4.951-1.488A3.987 3.987 0 0 1 9 13h2a3.987 3.987 0 0 1 3.951 3.512A8.949 8.949 0 0 1 10 18Z"/>
                    </svg>
                    Редактирование мероприятий </a>
            </li>
            <li>
                <a href="{% url 'activities:list_requests_activities_staff' %}"
                   class="inline-flex items-center px-4 py-3 active w-full

       {% if view_name == 'activities:list_requests_activities_staff' %}
                                                                                text-green-400
                                                                                {% else %}
                                                                                text-gray-300
                                                                                {% endif %}
" id="dropdownHoverButton" data-dropdown-toggle="dropdownHover" data-dropdown-trigger="hover"
                   aria-current="page">
                    <svg class="w-4 h-4 me-2 text-gray-300" aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg"
                         fill="currentColor" viewBox="0 0 20 20">
                        <path d="M10 0a10 10 0 1 0 10 10A10.011 10.011 0 0 0 10 0Zm0 5a3 3 0 1 1 0 6 3 3 0 0 1 0-6Zm0 13a8.949 8.949 0 0 1-4.951-1.488A3.987 3.987 0 0 1 9 13h2a3.987 3.987 0 0 1 3.951 3.512A8.949 8.949 0 0 1 10 18Z"/>
                    </svg>
                    Заявки мероприятий </a>




<!-- Dropdown menu -->
<div id="dropdownHover" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
    <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownHoverButton">
        {% for value, display_name in enum_activities %}
            <li> <a class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                                       href="{% url 'activities:list_requests_activities_staff' %}?q={{ value }}">{{ display_name }}</a></li>
        {% endfor %}
    </ul>

</div>


            </li>


        </ul>
    {% endwith %}
</div>